source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/TuyaInc/TYPublicSpecs.git'

target 'TYModuleManagerExample_Example' do
  pod 'TYModuleManagerExample', :path => '../'
  
#  pod 'TYModuleManager', :path => '../../TYModuleManager'
#  pod 'TYModuleTabbar', :path => '../../TYModuleTabbar'

end
